
name: go

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: [ '1.23.x' ]
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: make build-all
    - name: Test
      run: make test ARGS="--json --fail-on-error" > TestResults-${{ matrix.go-version }}.json
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
    


